version: '3.7'
services:
  web:
    image: mediawiki:latest
    ports:
      - 8080:80
    links:
      - database
    restart: unless-stopped
    volumes:
      - ./images:/var/www/html/images
      - ./LocalSettings.php:/var/www/html/LocalSettings.php
      - ./php:/usr/local/etc/php
#      - ./www:/var/www
#      - ./uploads.ini:/etc/php5/fpm/conf.d/uploads.ini:ro

  database:
    image: mariadb
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: 'wiki'
      MYSQL_USER: 'wikiuser234234'
      MYSQL_PASSWORD: 'YOUR_SECURE_PASSWORD'
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
    volumes:
      - ./database:/var/lib/mysql
    restart: unless-stopped
volumes:
  dbdata:
    driver: local